CM changes: standalone builds, better CMB.make/deliver, general improvements

diff --git a/sml/src/system/makeml b/sml/src/system/makeml
--- a/sml/src/system/makeml
+++ b/sml/src/system/makeml
@@ -1,17 +1,24 @@
 #!/bin/sh
-#
+
+here=`pwd`
+cd ../..
+twoup=`pwd`
+cd $here
+
+LINK=$twoup/bin/.link-sml
+
+if [ ! -x $LINK ] ; then
+    echo Link script $LINK is not operational.
+    exit 1
+fi
 
 ALLOC=1M
-
 ARCH=sparc
-OPSYS=solaris
-RUN_DIR=../../bin/.run
-OBJS_DIR=../runtime/objs
-HEAP_IMAGE=""
-RUN=""
-RUN_ARGS=""
+HEAP="sml"
+ARGS=""
 MODE=""
-BOOT_DIR=""
+RUN=""
+
 rebuilt=no
 bare=no
 
@@ -20,27 +27,52 @@ bare=no
 # (using an absolute path!)
 #
 
-here=`pwd`
-cd ../..
-CM_PATHCONFIG_DEFAULT=`pwd`/lib/pathconfig
-cd $here
+CM_PATHCONFIG_DEFAULT=$twoup/lib/pathconfig
 export CM_PATHCONFIG_DEFAULT
 
 #
 # use the arch-n-opsys script to determine the ARCH/OS if possible
 #
-if [ -f ../../bin/.arch-n-opsys ]; then
-  ARCH_N_OPSYS=`../../bin/.arch-n-opsys`
-  if [ "$?" = "0" ]; then
-    eval $ARCH_N_OPSYS
-	echo $ARCH $OPSYS
-  fi
+if [ -f $twoup/bin/.arch-n-opsys ]; then
+    ARCH_N_OPSYS=`$twoup/bin/.arch-n-opsys`
+    if [ "$?" = "0" ]; then
+	eval $ARCH_N_OPSYS
+	echo Architecture: $ARCH
+    fi
 fi
 
-while [ "$#" != "0" ]
-do
-  arg=$1; shift
-  case $arg in
+link() {
+    if [ -d $1 ] ; then
+	if [ ! -d $2 ] ; then
+	    if [ -f $2 ] ; then
+		echo makeml: $2 exists as a non-directory.
+		exit 1
+	    fi
+	    mkdir $2
+	fi
+	cd $1
+	for i in * ; do
+	    link $i $2/$i
+	done
+	cd ..
+    elif [ -f $1 ] ; then
+	rm -f $2
+	ln $1 $2
+    fi
+}
+
+BOOT_DIR="sml.boot.${ARCH}-unix"
+
+while [ "$#" != "0" ] ; do
+    arg=$1; shift
+    case $arg in
+    -run)
+	if [ "$#" = "0" ]; then
+	    echo "makeml: missing argument for \"-run\" option"
+	    exit 1
+	fi
+	RUN="@SMLrun=$1"; shift
+	;;
     -bare)
 	bare=yes
 	MODE="@SMLbare"
@@ -53,33 +85,12 @@ do
 	rebuilt=yes
 	MODE="@SMLrebuild=$1"; shift
 	;;
-    -arch)
-	if [ "$#" = "0" ]; then
-	    echo "makeml: missing argument for \"-arch\" option"
-	    exit 1
-	fi
-	ARCH=$1; shift
-	;;
-    -opsys)
-	if [ "$#" = "0" ]; then
-	    echo "makeml: missing argument for \"-opsys\" option"
-	    exit 1
-	fi
-	OPSYS=$1; shift
-	;;
     -o)
 	if [ "$#" = "0" ]; then
 	    echo "makeml: missing argument for \"-o\" option"
 	    exit 1
 	fi
-	HEAP_IMAGE=$1; shift
-	;;
-    -run)
-	if [ "$#" = "0" ]; then
-	    echo "makeml: missing argument for \"-run\" option"
-	    exit 1
-	fi
-	RUN=$1; shift
+	HEAP=$1; shift
 	;;
     -alloc)
 	if [ "$#" = "0" ]; then
@@ -96,7 +107,7 @@ do
 	BOOT_DIR=$1; shift
 	;;
     @SML*)
-	RUN_ARGS="$RUN_ARGS $arg"
+	ARGS="$ARGS $arg"
 	;;
     *)
 	echo "makeml: unknown argument \"$arg\""
@@ -105,35 +116,12 @@ do
     esac
 done
 
-if [ x"$RUN" = x ]; then
-  if [ x"$OPSYS" = xwin32 ]; then
-    RUN_CMD="run.$ARCH-$OPSYS.exe"
-  else
-    RUN_CMD="run.$ARCH-$OPSYS"
-  fi
-  if [ -x "$RUN_DIR/$RUN_CMD" ]; then
-    RUN="$RUN_DIR/$RUN_CMD"
-  elif [ -x "$OBJS_DIR/$RUN_CMD" ]; then
-    RUN="$OBJS_DIR/$RUN_CMD"
-  else
-    echo "makeml: unable to find run-time system \"$RUN_CMD\""
-    exit 1
-  fi
-fi
+cd $BOOT_DIR
 
-if [ x"$HEAP_IMAGE" = x ]; then
-  HEAP_IMAGE="sml"
-fi
-
-if [ x"$BOOT_DIR" = x ]; then
-  BOOT_DIR="./sml.boot.$ARCH-unix"
-fi
-
-echo "$RUN @SMLboot=$BOOT_DIR @SMLrtpid=`cat $BOOT_DIR/RTPID` \
-	@SMLheap=$HEAP_IMAGE @SMLalloc=$ALLOC $RUN_ARGS $MODE"
-
-if $RUN @SMLboot=$BOOT_DIR @SMLrtpid=`cat $BOOT_DIR/RTPID` \
-	@SMLheap=$HEAP_IMAGE @SMLalloc=$ALLOC $RUN_ARGS $MODE
+echo $LINK $RUN \
+    @SMLboot=BOOTLIST @SMLheap=$here/$HEAP @SMLalloc=$ALLOC $ARGS $MODE
+if $LINK $RUN \
+    @SMLboot=BOOTLIST @SMLheap=$here/$HEAP @SMLalloc=$ALLOC $ARGS $MODE
 then
 #
 # If this was a -rebuild run, we have to quit now...
@@ -152,19 +140,19 @@ fi
 # Now move the libraries, generate the pathconfig file, and delete the bootdir.
 #
 
+cd $here
 if [ $bare = no ] ; then
-    LIB_DIR=`pwd`/${HEAP_IMAGE}.lib
+    LIB_DIR=`pwd`/${HEAP}.lib
 
     rm -rf $LIB_DIR
     mkdir $LIB_DIR
 
     cd $BOOT_DIR
 
-    for i in *.cm ; do
-	mv $i $LIB_DIR/$i
+    for i in init.cmi *.cm ; do
+	link $i $LIB_DIR/$i
 	echo $i $i
     done >$LIB_DIR/pathconfig
 
-    cd ..
-    rm -r $BOOT_DIR
+    cd $here
 fi
