This commit was generated by cvs2svn to compensate for changes in r106,
which included commits to RCS files with non-trunk default branches.

diff --git a/sml/config/_run-sml b/sml/config/_run-sml
--- a/sml/config/_run-sml
+++ b/sml/config/_run-sml
@@ -80,6 +80,18 @@ if [ "$RUN" = "" ]; then
   # Construct the runtime system path from the ARCH and OS
   #
   RUN="$RUN_DIR/run.$ARCH-$OPSYS"
+  if [ ! -x "$RUN" ]; then
+    if [ "$ALT_OPSYS" = "" ]; then
+      echo "$CMD: cannot find runtime system $RUN"
+      exit 1
+    else
+      RUN="$RUN_DIR/run.$ARCH-$ALT_OPSYS"
+      if [ ! -x "$RUN" ]; then
+	echo "$CMD: cannot find runtime system $RUN"
+	exit 1
+      fi
+    fi
+  fi
 fi
 
 if [ "$HEAP" = "" ]; then
@@ -90,11 +102,6 @@ if [ "$HEAP" = "" ]; then
     APPL=$CMD
   fi
   HEAP="@SMLload=$HEAP_DIR/$APPL"
-fi
-
-if [ ! -x "$RUN" ]; then
-  echo "$CMD: cannot find runtime system $RUN"
-  exit 1
 fi
 
 #
